name: Auto Move Algo Files with Nickname Mapping

on:
  push:
    branches:
      - main
    paths:
      - '프로그래머스/**'
      - 'SWEA/**'

jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Move files with nickname mapping
        run: |
          ACTOR="${{ github.actor }}"
          
          case "$ACTOR" in
            "sonyeseul63") FOLDER="ysson" ;;
          esac
          
          echo "Moving files for $ACTOR to folder: $FOLDER"
          
          if [ -d "프로그래머스" ]; then
            TARGET_DIR="$FOLDER/PROG"
            mkdir -p "$TARGET_DIR"
            cp -r 프로그래머스/* "$TARGET_DIR/"
            rm -rf 프로그래머스
          fi

          # if [ -d "SWEA" ]; then
          #   TARGET_DIR="$FOLDER/SWEA"
          #   mkdir -p "$TARGET_DIR"
          #   cp -r SWEA/* "$TARGET_DIR/"
          #   rm -rf SWEA
          # fi

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: move solved problems for ${{ github.actor }}" || exit 0
          git push
